version: '3.1'

services:
  
  node0:
    build: 
      context: ./
      dockerfile: Dockerfile0
    image: chromia/postchain:chromunity-0
    ports:
      - 7740:7740
    tty: true
    depends_on:
      - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node1:
    build: 
      context: ./
      dockerfile: Dockerfile1
    image: chromia/postchain:chromunity-1
    ports:
      - 7741:7740
    tty: true
    depends_on:
      - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node2:
    build: 
      context: ./
      dockerfile: Dockerfile2
    image: chromia/postchain:chromunity-2
    ports:
      - 7742:7740
    tty: true
    depends_on:
      - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node3:
    build: 
      context: ./
      dockerfile: Dockerfile3
    image: chromia/postchain:chromunity-3
    ports:
      - 7743:7740
    tty: true
    depends_on:
      - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
     

  postgres_db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}