apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    apps: postgres-db
  name: postgres-db
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: postgres-db
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/postchain-network: "true"
        apps: postgres-db
    spec:
      containers:
      - env:
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postchain-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postchain-env
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_USER
              name: postchain-env
        image: postgres:10-alpine
        name: postgres-db
        ports:
        - containerPort: 5432
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
---
apiVersion: v1
kind: Service
metadata:
  labels:
    apps: postgres-db
  name: postgres-db
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    apps: postgres-db