---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  creationTimestamp: null
  labels:
    apps: node1
  name: node1
spec:
  replicas: 1
  selector:
    matchLabels:
      apps: node1
  strategy: {}
  template:
    metadata:
      annotations:
      labels:
        io.kompose.network/postchain-network: "true"
        apps: node1
    spec:
      containers:
      - env:
        - name: PGHOST
          valueFrom:
            configMapKeyRef:
              key: PGHOST
              name: postchain-env
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_DB
              name: postchain-env
        - name: POSTGRES_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: POSTGRES_PASSWORD
              name: postchain-env
        image: chromia/postchain:chromunity-1
        imagePullPolicy: ""
        name: node1
        ports:
        - containerPort: 7740
        resources: {}
        tty: true
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    apps: node1
  name: node1
spec:
  ports:
  - name: "9870"
    port: 9870
    targetPort: 9870
  selector:
    apps: node1
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    apps: node1
  name: ext-node1
spec:
  type: NodePort
  ports:
  - name: "7740"
    port: 7740
    targetPort: 7740
  selector:
    apps: node1