version: '3.1'

services:
  {% for node in nodes %}
  node{{node.id}}:
    build: 
      context: ./
      dockerfile: Dockerfile{{node.id}}
    image: {{ docker_image }}-{{node.id}}
    ports:
      - 774{{node.id}}:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  {% endfor %}   

  # postgres_db:
  #   image: postgres:10-alpine
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}
