version: '3.1'

services:
  node0:
    build: 
      context: ./
      dockerfile: Dockerfile0
    image: public.ecr.aws/j8l1p8n9/chromia/d1test:node-0
    ports:
      - 7740:7740
    tty: true
    depends_on:
      - postgres_db
    # restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  postgres_db:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
  adminer:
    image: adminer
    restart: always
    ports:
      - 8089:8080