version: '3.1'

services:
  
  node1:
    build: 
      context: ./
      dockerfile: Dockerfile1
    image: public.ecr.aws/j8l1p8n9/chromia/d1test:node-1
    ports:
      - 7741:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node2:
    build: 
      context: ./
      dockerfile: Dockerfile2
    image: public.ecr.aws/j8l1p8n9/chromia/d1test:node-2
    ports:
      - 7742:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node3:
    build: 
      context: ./
      dockerfile: Dockerfile3
    image: public.ecr.aws/j8l1p8n9/chromia/d1test:node-3
    ports:
      - 7743:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
     

  # postgres_db:
  #   image: postgres:10-alpine
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}