version: '3.1'

services:
  
  node1:
    build: 
      context: ./
      dockerfile: Dockerfile1
    image: chromia/postchain:d1test-generator-1
    ports:
      - 7741:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node2:
    build: 
      context: ./
      dockerfile: Dockerfile2
    image: chromia/postchain:d1test-generator-2
    ports:
      - 7742:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node3:
    build: 
      context: ./
      dockerfile: Dockerfile3
    image: chromia/postchain:d1test-generator-3
    ports:
      - 7743:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node4:
    build: 
      context: ./
      dockerfile: Dockerfile4
    image: chromia/postchain:d1test-generator-4
    ports:
      - 7744:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node5:
    build: 
      context: ./
      dockerfile: Dockerfile5
    image: chromia/postchain:d1test-generator-5
    ports:
      - 7745:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node6:
    build: 
      context: ./
      dockerfile: Dockerfile6
    image: chromia/postchain:d1test-generator-6
    ports:
      - 7746:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node7:
    build: 
      context: ./
      dockerfile: Dockerfile7
    image: chromia/postchain:d1test-generator-7
    ports:
      - 7747:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node8:
    build: 
      context: ./
      dockerfile: Dockerfile8
    image: chromia/postchain:d1test-generator-8
    ports:
      - 7748:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
  
  node9:
    build: 
      context: ./
      dockerfile: Dockerfile9
    image: chromia/postchain:d1test-generator-9
    ports:
      - 7749:7740
    tty: true
    # depends_on:
    #   - postgres_db
    restart: always
    env_file:
      - .env
    environment:
      PGHOST: ${PGHOST}
     

  # postgres_db:
  #   image: postgres:10-alpine
  #   environment:
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  #     POSTGRES_USER: ${POSTGRES_USER}
  #     POSTGRES_DB: ${POSTGRES_DB}